### ISSUE TITLE
Remove line number from ERROR_COUNTER metric

### ISSUE THREAD

**Issue by jeffbakerexpedia** [ExpediaDotCom/haystack-logback-metrics-appender#28]
Scaling issues with InfluxDb have led us to change the way that Graphite messages are changed into tagged metrics in InfluxDb; in particular, the InfluxDb template for the error metrics was changed from "haystack.errors.*  system.metricGroup.subsystem.fqClass.host.lineNumber.measurement*" to "haystack.errors.*  measurement.measurement.measurement.fqClass.host.field*". As a result, the presence of line number in the metric needs to be removed. In the interest of simplicity, I will comment out the code that inserts line number into the Graphite metric, to facilitate a potential setting-based change in the future to allow this package to create both types of Graphite metrics.

**Comment by LakerBaker** [comment]
Changes made.
